pipeline {
    agent any

    parameters {
        string(
            name: "DOMAIN_NAME"
        )
    }

    stages {
        stage('Clone') {
            steps {
                checkout scm
                sh """
                    echo 'domain_name = \"$DOMAIN_NAME\"' > infra/terraform.tfvars
                """
            }
        }

        stage('Validar') {
            // Con checkov
            steps {
                echo 'Validando...'
            }
        }

        stage('Inicializar terraform') {
            steps {
                withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'my_aws_credential']]) {
                    sh 'terraform -chdir=infra/ init'
                }
            }
        }

        stage('Provisionar') {
            steps {
                withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'my_aws_credential']]) {
                    sh """
                        export AWS_REGION="us-east-2"
                        terraform -chdir=infra/ apply -auto-approve
                    """
                }
            }
        }
    }
}