pipeline {
    agent any

    parameters {
        string(
            name: "DOMAIN_NAME"
        )
    }

    stages {
        stage('Clone') {
            steps {
                checkout scm
                echo 'echo domain_name = "$DOMAIN_NAME" > infra/terraform.tfvars'
            }
        }

        stage('Plan') {
            steps {
                withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'my_aws_credential']]) {
                    sh 'terraform -chdir=infra/ init'
                    sh 'terraform -chdir=infra/ plan'
                }
            }
        }
    }
}