- name: Desplegar mcsrvc reservas
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/.."
    account_id: "{{ lookup('pipe', 'terraform -chdir=../infra/ output -raw aws-account-id') }}"
    msrvc_root: "{{project_root}}/services/reservas"

  tasks:
    - name: autenticar cliente de docker
      shell: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin {{account_id}}.dkr.ecr.us-east-2.amazonaws.com

    - name: construir mcsrvc
      command: docker build -t msrvc/reservas {{msrvc_root}}
    
    - name: tag image
      command: docker tag msrvc/reservas:latest {{account_id}}.dkr.ecr.us-east-2.amazonaws.com/msrvc/reservas:latest
    
    - name: push image
      command: docker push {{account_id}}.dkr.ecr.us-east-2.amazonaws.com/msrvc/reservas:latest