FROM ubuntu:24.04

USER root

# GIT
RUN apt update
RUN apt install -y git

# TERRAFORM
RUN apt-get update
RUN apt-get install -y gnupg software-properties-common

RUN apt-get install wget
RUN <<EOF
    wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
EOF

RUN gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

RUN echo "deb [arch=$(dpkg --print-architecture)\
        signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]\
        https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*'\
         /etc/os-release || lsb_release -cs) main"\
        | tee /etc/apt/sources.list.d/hashicorp.list

RUN apt update
RUN apt-get install terraform=1.13.1-1