FROM ubuntu:24.04

USER root

# GIT
RUN apt update
RUN apt install -y git

# ANSIBLE
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt install -y ansible=12.2.0-1ppa~noble

# AWS CLI
RUN apt install -y curl
RUN apt install -y unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.30.1.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

# ZIP
RUN apt-get install zip

# NPM
RUN apt-get install -y npm
RUN npm install -g npm@10.9.3

# Docker CLI
RUN apt-get update
RUN apt-get install ca-certificates curl
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
RUN chmod a+r /etc/apt/keyrings/docker.asc

RUN <<TOR
tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF
TOR

RUN apt-get update
RUN apt-cache policy docker-ce-cli
RUN apt-get install -y docker-ce-cli=5:28.4.0-1~ubuntu.24.04~noble