FROM ubuntu:22.04

USER root

# GIT
RUN apt update
RUN apt install -y git

# ANSIBLE
RUN apt update
RUN apt install software-properties-common
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt install ansible=2.18.9

# AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.30.1.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install